apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
 name: usagerecord.susecloud.net
spec:
 group: susecloud.net
 names:
   plural: usagerecords
   singular: usagerecord
   kind: UsageRecord
   shortNames:
   - ur
 scope: Cluster
 versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           value:
             type: int
           version:
             type: string
